const GfxType = {
  Interface1: 1,
  Interface2: 2,
  MapGroundTiles: 3,
  MapObjects: 4,
  MapOverlayTiles: 5,
  MapWalls: 6,
  MapRoofTiles: 7,
  CharacterSprites: 8,
  MaleHair: 9,
  FemaleHair: 10,
  MaleBoots: 11,
  FemaleBoots: 12,
  MaleArmor: 13,
  FemaleArmor: 14,
  MaleHats: 15,
  FemaleHats: 16,
  MaleWeapons: 17,
  FemaleWeapons: 18,
  MaleShields: 19,
  FemaleShields: 20,
  NpcSprites: 21,
  MapShadows: 22,
  ItemSprites: 23,
  SpellAnimations: 24,
  SpellIcons: 25,
};

export default GfxType;
